name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 5 * * *'
jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [8, 11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Run tests
      run: |
        sbt "+ test" "+ unidoc"
        git diff --exit-code
